CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
GPUS: (0,)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
EXPERIMENT_NAME: 'default'
WORKERS: 4
PRINT_FREQ: 10
DATASET:
  TRAIN_SET: 'train.txt'
  TEST_SET: 'test.txt'
  VAL_SET: 'val.txt'
  NUM_CLASSES: 4
  NUM_INPUT_CHANNELS: 1
  CLASS_WEIGHTS:
  - 0.89655424
  - 0.97887961
  - 1.10006676
  - 1.02449939
MODEL:
  NAME: hrnet
  PRETRAINED: 'pretrained_models/hrnetv2_w48_imagenet_pretrained.pth'
LOSS:
  USE_OHEM: True
TRAIN:
  BASE_SIZE: 1200
  BATCH_SIZE_PER_GPU: 5
  EPOCHS: 100
  IGNORE_LABEL: -1
  IMAGE_SIZE: [1000, 1000]
  INIT_FN: xavier_normal_
  LR: 0.01
  LR_FACTOR: 0.1
  LR_STEP: [90, 110]
  MOMENTUM: 0.9
  MULTI_SCALE: True
  NESTEROV: False
  NUM_SAMPLES: 0
  OPTIMIZER: SGD
  RESUME: True
  SCALE_FACTOR: 11
  SHUFFLE: True
  WD: 0.001
TEST:
  IMAGE_SIZE:
  - 1200
  - 1200
  BASE_SIZE: 1200
  BATCH_SIZE_PER_GPU: 1
  MULTI_SCALE: False

